use_frameworks!

platform :ios, '12.0'

target 'UBiXMediationSDK_Example' do
  # 即刻聚合
#  pod 'UBiXMediationSDK', :path => '../'
   pod 'UBiXMediationSDK', '2.5.0'

#  pod 'Ads-CN', '5.8.0.9'
#  pod 'Ads-Global', '5.7.0.7'
   # gromore 融合
   pod 'Ads-CN-Beta/BUAdSDK','6.1.1.0'
   pod 'Ads-CN-Beta/CSJMediation','6.1.1.0'
   # 优量汇
   pod 'GDTMobSDK', '4.14.76'
   # 快手
   pod 'KSAdSDK', '3.3.65'
   # 百度
   pod 'UBiXMBaiduAdapter', '5.35.0.0'
#   pod 'BaiduMobAdSDK', '5.35'
   # 京东
   pod 'JADYun', '2.5.12'
   pod 'JADYunMotion', '2.5.12'
  # 天璇
  pod 'UBiXMerakSDK', '2.3.4'



  target 'UBiXMediationSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end

post_install do |installer|
  # fix xcode 15 DT_TOOLCHAIN_DIR - remove after fix oficially - https://github.com/CocoaPods/CocoaPods/issues/12065
  installer.aggregate_targets.each do |target|
      target.xcconfigs.each do |variant, xcconfig|
      xcconfig_path = target.client_root + target.xcconfig_relative_path(variant)
      IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
      end
  end

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.base_configuration_reference.is_a? Xcodeproj::Project::Object::PBXFileReference
          xcconfig_path = config.base_configuration_reference.real_path
          IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
      end
    end
  end
end


