use_frameworks!

platform :ios, '10.0'

target 'UBiXMediationSDK_Example' do
  pod 'UBiXMediationSDK', :path => '../'

  target 'UBiXMediationSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
