// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mediation_cofing_api_v2.0.0.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(UbiX_GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define UbiX_GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if UbiX_GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/UbiXGPBProtocolBuffers.h>
#else
 #import <UbiXDaq/UbiXGPBProtocolBuffers.h>
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class MubixConfigRequest_MubixAppInfo;
@class MubixConfigRequest_MubixDeviceInfo;
@class MubixConfigRequest_MubixDeviceInfo_MubixGeo;
@class MubixConfigRequest_MubixMediationSlot;
@class MubixConfigRequest_MubixMultiDimensionStatistics;
@class MubixConfigRequest_MubixMultiDimensionStatistics_MubixDimensionValue;
@class MubixConfigRequest_MubixSize;
@class MubixConfigRequest_MubixUserInfo;
@class MubixConfigResponse;
@class MubixConfigResponse_MubixStrategy;
@class MubixConfigResponse_MubixStrategy_MubixAdPreCache;
@class MubixDeviceId;
@class MubixSdkConfig;
@class MubixSdkConfig_ShakingConfig;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum MubixChannel

typedef UbiX_GPB_ENUM(MubixChannel) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  MubixChannel_GPBUnrecognizedEnumeratorValue = kUbiXGPBUnrecognizedEnumeratorValue,
  /** 无用，占位 */
  MubixChannel_MubixSdkChannelUnknown = 0,

  /** 其他 */
  MubixChannel_MubixSdkChannelOthers = 1,

  /** oppo */
  MubixChannel_MubixSdkChannelOppo = 2,

  /** vivo */
  MubixChannel_MubixSdkChannelVivo = 3,

  /** 华为 */
  MubixChannel_MubixSdkChannelHuawei = 4,

  /** 小米 */
  MubixChannel_MubixSdkChannelXiaomi = 5,

  /** 荣耀 */
  MubixChannel_MubixSdkChannelHonor = 6,

  /** 腾讯MP */
  MubixChannel_MubixSdkChannelTencentMp = 7,

  /** 百度 */
  MubixChannel_MubixSdkChannelBaidu = 8,

  /** 快手 */
  MubixChannel_MubixSdkChannelKuaishou = 9,
};

UbiXGPBEnumDescriptor *MubixChannel_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL MubixChannel_IsValidValue(int32_t value);

#pragma mark - Enum MubixAdType

typedef UbiX_GPB_ENUM(MubixAdType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  MubixAdType_GPBUnrecognizedEnumeratorValue = kUbiXGPBUnrecognizedEnumeratorValue,
  /** 无用，占位 */
  MubixAdType_MubixAdTypeUnknown = 0,

  /** 开屏 */
  MubixAdType_MubixAdTypeSplash = 1,

  /** 信息流 */
  MubixAdType_MubixAdTypeFeed = 2,

  /** 激励视频 */
  MubixAdType_MubixAdTypeRewardVideo = 3,

  /** 横幅 */
  MubixAdType_MubixAdTypeBanner = 4,

  /** 插屏 */
  MubixAdType_MubixAdTypeInterstitial = 5,

  /** 全屏视频 */
  MubixAdType_MubixAdTypeFullVideo = 6,

  /** 贴片 */
  MubixAdType_MubixAdTypePaster = 7,
};

UbiXGPBEnumDescriptor *MubixAdType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL MubixAdType_IsValidValue(int32_t value);

#pragma mark - MediationCofingApiV200Root

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (UbiXGPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c UbiXGPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
UbiX_GPB_FINAL @interface MediationCofingApiV200Root : UbiXGPBRootObject
@end

#pragma mark - MubixPresetConfigRequest

typedef UbiX_GPB_ENUM(MubixPresetConfigRequest_FieldNumber) {
  MubixPresetConfigRequest_FieldNumber_AppId = 1,
  MubixPresetConfigRequest_FieldNumber_Token = 2,
  MubixPresetConfigRequest_FieldNumber_Timestamp = 3,
};

/**
 * 预置配置请求
 **/
UbiX_GPB_FINAL @interface MubixPresetConfigRequest : UbiXGPBMessage

/** 流量应用ID */
@property(nonatomic, readwrite) int64_t appId;

/** 加密串 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

/** 时间戳 */
@property(nonatomic, readwrite) int64_t timestamp;

@end

#pragma mark - MubixPresetConfigResponse

typedef UbiX_GPB_ENUM(MubixPresetConfigResponse_FieldNumber) {
  MubixPresetConfigResponse_FieldNumber_MubixConfigsArray = 1,
};

/**
 * 预置配置返回
 **/
UbiX_GPB_FINAL @interface MubixPresetConfigResponse : UbiXGPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MubixConfigResponse*> *mubixConfigsArray;
/** The number of items in @c mubixConfigsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger mubixConfigsArray_Count;

@end

#pragma mark - MubixConfigRequest

typedef UbiX_GPB_ENUM(MubixConfigRequest_FieldNumber) {
  MubixConfigRequest_FieldNumber_MubixSdkVersion = 1,
  MubixConfigRequest_FieldNumber_MubixApp = 2,
  MubixConfigRequest_FieldNumber_MubixDevice = 3,
  MubixConfigRequest_FieldNumber_MubixTimestamp = 5,
  MubixConfigRequest_FieldNumber_MubixMediationSlot = 6,
  MubixConfigRequest_FieldNumber_MubixLogReady = 7,
  MubixConfigRequest_FieldNumber_MubixInstalledAppsArray = 9,
  MubixConfigRequest_FieldNumber_MubixRequestId = 10,
  MubixConfigRequest_FieldNumber_MubixStrategyMd5Id = 11,
  MubixConfigRequest_FieldNumber_MubixUserInfo = 12,
};

UbiX_GPB_FINAL @interface MubixConfigRequest : UbiXGPBMessage

/** 必填。当前sdk的版本。格式如：1.0.0 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixSdkVersion;

/** 必填。移动app的信息。 */
@property(nonatomic, readwrite, strong, null_resettable) MubixConfigRequest_MubixAppInfo *mubixApp;
/** Test to see if @c mubixApp has been set. */
@property(nonatomic, readwrite) BOOL hasMubixApp;

/** 必填。移动设备的信息。 */
@property(nonatomic, readwrite, strong, null_resettable) MubixConfigRequest_MubixDeviceInfo *mubixDevice;
/** Test to see if @c mubixDevice has been set. */
@property(nonatomic, readwrite) BOOL hasMubixDevice;

/** 触发时间 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixTimestamp;

/** 聚合广告位列表 */
@property(nonatomic, readwrite, strong, null_resettable) MubixConfigRequest_MubixMediationSlot *mubixMediationSlot;
/** Test to see if @c mubixMediationSlot has been set. */
@property(nonatomic, readwrite) BOOL hasMubixMediationSlot;

/** false: 无错误日志, true: 存在错误日志 */
@property(nonatomic, readwrite) BOOL mubixLogReady;

/** 获得的安装的应用ID列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *mubixInstalledAppsArray;
/** The number of items in @c mubixInstalledAppsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger mubixInstalledAppsArray_Count;

/** 广告请求的requestID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixRequestId;

/** 本地保存的策略的MD5唯一值 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixStrategyMd5Id;

/** 用户信息 */
@property(nonatomic, readwrite, strong, null_resettable) MubixConfigRequest_MubixUserInfo *mubixUserInfo;
/** Test to see if @c mubixUserInfo has been set. */
@property(nonatomic, readwrite) BOOL hasMubixUserInfo;

@end

#pragma mark - MubixConfigRequest_MubixMediationSlot

typedef UbiX_GPB_ENUM(MubixConfigRequest_MubixMediationSlot_FieldNumber) {
  MubixConfigRequest_MubixMediationSlot_FieldNumber_MubixSlotId = 1,
  MubixConfigRequest_MubixMediationSlot_FieldNumber_MubixUvSlotDailyReq = 2,
  MubixConfigRequest_MubixMediationSlot_FieldNumber_MubixUvSlotDailyImp = 3,
  MubixConfigRequest_MubixMediationSlot_FieldNumber_MubixUvSlotDailyClick = 4,
  MubixConfigRequest_MubixMediationSlot_FieldNumber_MubixSdkSlotUvReq = 5,
  MubixConfigRequest_MubixMediationSlot_FieldNumber_MubixSdkSlotUvImp = 6,
  MubixConfigRequest_MubixMediationSlot_FieldNumber_MubixSdkSlotUvClick = 7,
  MubixConfigRequest_MubixMediationSlot_FieldNumber_MubixAdType = 8,
  MubixConfigRequest_MubixMediationSlot_FieldNumber_MubixSplashStartMode = 9,
  MubixConfigRequest_MubixMediationSlot_FieldNumber_MubixStrategyMd5Id = 10,
  MubixConfigRequest_MubixMediationSlot_FieldNumber_MubixRequestId = 11,
};

UbiX_GPB_FINAL @interface MubixConfigRequest_MubixMediationSlot : UbiXGPBMessage

/** 聚合广告位id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixSlotId;

/** 单广告位总请求数 */
@property(nonatomic, readwrite) int64_t mubixUvSlotDailyReq;

/** 单广告位总曝光数 */
@property(nonatomic, readwrite) int64_t mubixUvSlotDailyImp;

/** 单广告位总点击数 */
@property(nonatomic, readwrite) int64_t mubixUvSlotDailyClick;

/** 第三方sdk代码位请求不同时间维度计数 key: 第三方sdk代码位 value: 不同维度请求计数列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, MubixConfigRequest_MubixMultiDimensionStatistics*> *mubixSdkSlotUvReq;
/** The number of items in @c mubixSdkSlotUvReq without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger mubixSdkSlotUvReq_Count;

/** 第三方sdk代码位曝光不同时间维度计数 key: 第三方sdk代码位 value: 不同维度请求计数列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, MubixConfigRequest_MubixMultiDimensionStatistics*> *mubixSdkSlotUvImp;
/** The number of items in @c mubixSdkSlotUvImp without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger mubixSdkSlotUvImp_Count;

/** 第三方sdk代码位点击不同时间维度计数 key: 第三方sdk代码位 value: 不同维度请求计数列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, MubixConfigRequest_MubixMultiDimensionStatistics*> *mubixSdkSlotUvClick;
/** The number of items in @c mubixSdkSlotUvClick without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger mubixSdkSlotUvClick_Count;

/** 请求的广告类型 */
@property(nonatomic, readwrite) MubixAdType mubixAdType;

/** 开屏的冷热启动。1：热启动；2：冷启动 */
@property(nonatomic, readwrite) int32_t mubixSplashStartMode;

/** 本地保存的策略的MD5唯一值 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixStrategyMd5Id;

/** 广告请求的requestID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixRequestId;

@end

/**
 * Fetches the raw value of a @c MubixConfigRequest_MubixMediationSlot's @c mubixAdType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t MubixConfigRequest_MubixMediationSlot_MubixAdType_RawValue(MubixConfigRequest_MubixMediationSlot *message);
/**
 * Sets the raw value of an @c MubixConfigRequest_MubixMediationSlot's @c mubixAdType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetMubixConfigRequest_MubixMediationSlot_MubixAdType_RawValue(MubixConfigRequest_MubixMediationSlot *message, int32_t value);

#pragma mark - MubixConfigRequest_MubixMultiDimensionStatistics

typedef UbiX_GPB_ENUM(MubixConfigRequest_MubixMultiDimensionStatistics_FieldNumber) {
  MubixConfigRequest_MubixMultiDimensionStatistics_FieldNumber_MubixDimensionValuesArray = 1,
};

UbiX_GPB_FINAL @interface MubixConfigRequest_MubixMultiDimensionStatistics : UbiXGPBMessage

/** 维度值列表（同时可以有多个维度的数据统计） */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MubixConfigRequest_MubixMultiDimensionStatistics_MubixDimensionValue*> *mubixDimensionValuesArray;
/** The number of items in @c mubixDimensionValuesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger mubixDimensionValuesArray_Count;

@end

#pragma mark - MubixConfigRequest_MubixMultiDimensionStatistics_MubixDimensionValue

typedef UbiX_GPB_ENUM(MubixConfigRequest_MubixMultiDimensionStatistics_MubixDimensionValue_FieldNumber) {
  MubixConfigRequest_MubixMultiDimensionStatistics_MubixDimensionValue_FieldNumber_MubixDimension = 1,
  MubixConfigRequest_MubixMultiDimensionStatistics_MubixDimensionValue_FieldNumber_MubixCount = 2,
};

UbiX_GPB_FINAL @interface MubixConfigRequest_MubixMultiDimensionStatistics_MubixDimensionValue : UbiXGPBMessage

/** 统计维度 1-每日 2-每小时 */
@property(nonatomic, readwrite) int32_t mubixDimension;

/** 计数 */
@property(nonatomic, readwrite) uint64_t mubixCount;

@end

#pragma mark - MubixConfigRequest_MubixAppInfo

typedef UbiX_GPB_ENUM(MubixConfigRequest_MubixAppInfo_FieldNumber) {
  MubixConfigRequest_MubixAppInfo_FieldNumber_MubixAppId = 1,
  MubixConfigRequest_MubixAppInfo_FieldNumber_MubixPackageName = 2,
  MubixConfigRequest_MubixAppInfo_FieldNumber_MubixVersion = 3,
  MubixConfigRequest_MubixAppInfo_FieldNumber_MubixChannel = 4,
  MubixConfigRequest_MubixAppInfo_FieldNumber_MubixInstallTime = 5,
};

UbiX_GPB_FINAL @interface MubixConfigRequest_MubixAppInfo : UbiXGPBMessage

/** 必填。媒体在ubix侧的应用ID。 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixAppId;

/** 必填。IOS填写bundleID，Android填写包名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixPackageName;

/** 必填。 app的版本信息。格式如：1.0.0 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixVersion;

/** 渠道来源 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixChannel;

/** 安装时间，unix时间戳，单位毫秒 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixInstallTime;

@end

#pragma mark - MubixConfigRequest_MubixDeviceInfo

typedef UbiX_GPB_ENUM(MubixConfigRequest_MubixDeviceInfo_FieldNumber) {
  MubixConfigRequest_MubixDeviceInfo_FieldNumber_MubixDid = 1,
  MubixConfigRequest_MubixDeviceInfo_FieldNumber_MubixDeviceType = 2,
  MubixConfigRequest_MubixDeviceInfo_FieldNumber_MubixOsType = 3,
  MubixConfigRequest_MubixDeviceInfo_FieldNumber_MubixOsVersion = 4,
  MubixConfigRequest_MubixDeviceInfo_FieldNumber_MubixVendor = 5,
  MubixConfigRequest_MubixDeviceInfo_FieldNumber_MubixModel = 6,
  MubixConfigRequest_MubixDeviceInfo_FieldNumber_MubixHwModel = 7,
  MubixConfigRequest_MubixDeviceInfo_FieldNumber_MubixHwMachine = 8,
  MubixConfigRequest_MubixDeviceInfo_FieldNumber_MubixLanguage = 9,
  MubixConfigRequest_MubixDeviceInfo_FieldNumber_MubixConnType = 10,
  MubixConfigRequest_MubixDeviceInfo_FieldNumber_MubixScreenSize = 11,
  MubixConfigRequest_MubixDeviceInfo_FieldNumber_MubixDpi = 12,
  MubixConfigRequest_MubixDeviceInfo_FieldNumber_MubixDeviceName = 13,
  MubixConfigRequest_MubixDeviceInfo_FieldNumber_MubixOrientation = 14,
  MubixConfigRequest_MubixDeviceInfo_FieldNumber_MubixCarrierType = 15,
  MubixConfigRequest_MubixDeviceInfo_FieldNumber_MubixCarrierCode = 16,
  MubixConfigRequest_MubixDeviceInfo_FieldNumber_MubixStartupTime = 18,
  MubixConfigRequest_MubixDeviceInfo_FieldNumber_MubixMbTime = 19,
  MubixConfigRequest_MubixDeviceInfo_FieldNumber_MubixCpuNum = 20,
  MubixConfigRequest_MubixDeviceInfo_FieldNumber_MubixDiskCapacity = 21,
  MubixConfigRequest_MubixDeviceInfo_FieldNumber_MubixMemCapacity = 22,
  MubixConfigRequest_MubixDeviceInfo_FieldNumber_MubixAuthStatus = 23,
  MubixConfigRequest_MubixDeviceInfo_FieldNumber_MubixBatteryPower = 24,
  MubixConfigRequest_MubixDeviceInfo_FieldNumber_MubixGeo = 25,
  MubixConfigRequest_MubixDeviceInfo_FieldNumber_MubixUa = 26,
  MubixConfigRequest_MubixDeviceInfo_FieldNumber_MubixHarmonyOsv = 27,
};

UbiX_GPB_FINAL @interface MubixConfigRequest_MubixDeviceInfo : UbiXGPBMessage

/** 设备ID信息。必填 */
@property(nonatomic, readwrite, strong, null_resettable) MubixDeviceId *mubixDid;
/** Test to see if @c mubixDid has been set. */
@property(nonatomic, readwrite) BOOL hasMubixDid;

/** 必填。设备类型。0: Unknown, 1: Phone, 2: Tablet */
@property(nonatomic, readwrite) int32_t mubixDeviceType;

/** 必填。操作系统类型。0: Unknown, 1: Android, 2: IOS */
@property(nonatomic, readwrite) int32_t mubixOsType;

/** 可选。操作系统版本。格式如：1.0.0 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixOsVersion;

/** 必填。设备厂商，如Apple, Samsung */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixVendor;

/** Android必填。设备机型名称，如：iPhone 11 Pro, Galaxy */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixModel;

/** IOS必填。IOS系统型号。比如：iPhone12,1。enrich时，通过官方映射表，取出对应的设备名称，赋值给model字段 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixHwModel;

/** IOS必填 cpu型号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixHwMachine;

/** 可选。设备设置的语言 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixLanguage;

/** 可选。设备的网络类型。0: Unknown, 1: Wifi, 2: 2G, 3: 3G, 4: 4G 5：5G */
@property(nonatomic, readwrite) int32_t mubixConnType;

/** 设备宽x高，单位：像素 */
@property(nonatomic, readwrite, strong, null_resettable) MubixConfigRequest_MubixSize *mubixScreenSize;
/** Test to see if @c mubixScreenSize has been set. */
@property(nonatomic, readwrite) BOOL hasMubixScreenSize;

/** 建议。屏幕密度 */
@property(nonatomic, readwrite) float mubixDpi;

/** 建议。手机名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixDeviceName;

/** 建议。设备屏幕方向。0: Unknown, 1: 竖屏, 2: 横屏 */
@property(nonatomic, readwrite) int32_t mubixOrientation;

/** 开发者不填写。移动运营商分类。0: Unknown, 1: Mobile, 2: Unicom, 3: Telecom */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixCarrierType;

/** 必填。由国际电联统一分配的移动运营商代码。MCC(3位) + MNC(2位) */
@property(nonatomic, readwrite) int32_t mubixCarrierCode;

/** 手机开机时间，如"1596270702.486691"，ios必传，Android推荐 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixStartupTime;

/** 系统版本更新时间，如"1596632447.155983"，ios必传，Android推荐 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixMbTime;

/** cpu数目，如"4"，ios必传，Android推荐 */
@property(nonatomic, readwrite) int32_t mubixCpuNum;

/** 磁盘容量大小（单位B）, ios必传，Android推荐 */
@property(nonatomic, readwrite) int64_t mubixDiskCapacity;

/** 内存容量大小（单位B）, ios必传，Android推荐 */
@property(nonatomic, readwrite) int64_t mubixMemCapacity;

/** 广告标志授权情况，如"3"（代表authorized），ios必传 */
@property(nonatomic, readwrite) int32_t mubixAuthStatus;

/** 设备电量百分比，取整数，数值区间 0~100。 */
@property(nonatomic, readwrite) int32_t mubixBatteryPower;

/** 地理位置 */
@property(nonatomic, readwrite, strong, null_resettable) MubixConfigRequest_MubixDeviceInfo_MubixGeo *mubixGeo;
/** Test to see if @c mubixGeo has been set. */
@property(nonatomic, readwrite) BOOL hasMubixGeo;

/** 选填。User-Agent 自定义User-Agent */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixUa;

/** 鸿蒙操作系统版本号（和android操作系统的os_version共存），格式：1.2.3 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixHarmonyOsv;

@end

#pragma mark - MubixConfigRequest_MubixDeviceInfo_MubixGeo

typedef UbiX_GPB_ENUM(MubixConfigRequest_MubixDeviceInfo_MubixGeo_FieldNumber) {
  MubixConfigRequest_MubixDeviceInfo_MubixGeo_FieldNumber_MubixLatitude = 1,
  MubixConfigRequest_MubixDeviceInfo_MubixGeo_FieldNumber_MubixLongitude = 2,
  MubixConfigRequest_MubixDeviceInfo_MubixGeo_FieldNumber_MubixLocalTzName = 3,
  MubixConfigRequest_MubixDeviceInfo_MubixGeo_FieldNumber_MubixCountry = 4,
  MubixConfigRequest_MubixDeviceInfo_MubixGeo_FieldNumber_MubixProvinceCode = 5,
  MubixConfigRequest_MubixDeviceInfo_MubixGeo_FieldNumber_MubixCityCode = 6,
  MubixConfigRequest_MubixDeviceInfo_MubixGeo_FieldNumber_MubixDistrictCode = 7,
};

UbiX_GPB_FINAL @interface MubixConfigRequest_MubixDeviceInfo_MubixGeo : UbiXGPBMessage

/** 推荐。GPS纬度 */
@property(nonatomic, readwrite) double mubixLatitude;

/** 推荐。GPS经度 */
@property(nonatomic, readwrite) double mubixLongitude;

/** local时区，如"Asia/Shanghai" */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixLocalTzName;

/** 国家代码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixCountry;

/** 省代码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixProvinceCode;

/** 城市代码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixCityCode;

/** 区代码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixDistrictCode;

@end

#pragma mark - MubixConfigRequest_MubixUserInfo

typedef UbiX_GPB_ENUM(MubixConfigRequest_MubixUserInfo_FieldNumber) {
  MubixConfigRequest_MubixUserInfo_FieldNumber_MubixUid = 1,
  MubixConfigRequest_MubixUserInfo_FieldNumber_MubixChannel = 2,
  MubixConfigRequest_MubixUserInfo_FieldNumber_MubixSubChannel = 3,
  MubixConfigRequest_MubixUserInfo_FieldNumber_MubixIsSubscriber = 6,
  MubixConfigRequest_MubixUserInfo_FieldNumber_MubixPubSegmentId = 7,
  MubixConfigRequest_MubixUserInfo_FieldNumber_MubixExt = 8,
};

/**
 * 用户信息。
 **/
UbiX_GPB_FINAL @interface MubixConfigRequest_MubixUserInfo : UbiXGPBMessage

/** 用户在媒体上注册的ID。 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixUid;

/** 渠道，由开发者自定义 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixChannel;

/** 子渠道，由开发者自定义 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixSubChannel;

/**
 *    int32  mubix_age = 4;     // 年龄。
 *    int32  mubix_gender = 5; //用户的性别，0: Unknown, 1: Male, 2: Female
 **/
@property(nonatomic, readwrite) int32_t mubixIsSubscriber;

/** 开发者的流量分组ID或者标签ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixPubSegmentId;

/** 自定义拓展参数，json格式。 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixExt;

@end

#pragma mark - MubixConfigRequest_MubixSize

typedef UbiX_GPB_ENUM(MubixConfigRequest_MubixSize_FieldNumber) {
  MubixConfigRequest_MubixSize_FieldNumber_MubixWidth = 1,
  MubixConfigRequest_MubixSize_FieldNumber_MubixHeight = 2,
};

/**
 * 尺寸
 **/
UbiX_GPB_FINAL @interface MubixConfigRequest_MubixSize : UbiXGPBMessage

/** 宽度。 */
@property(nonatomic, readwrite) uint32_t mubixWidth;

/** 高度。 */
@property(nonatomic, readwrite) uint32_t mubixHeight;

@end

#pragma mark - MubixDeviceId

typedef UbiX_GPB_ENUM(MubixDeviceId_FieldNumber) {
  MubixDeviceId_FieldNumber_MubixIdfa = 2,
  MubixDeviceId_FieldNumber_MubixIdfv = 3,
  MubixDeviceId_FieldNumber_MubixGxdi = 4,
  MubixDeviceId_FieldNumber_MubixImei = 5,
  MubixDeviceId_FieldNumber_MubixOaid = 6,
  MubixDeviceId_FieldNumber_MubixAid = 7,
  MubixDeviceId_FieldNumber_MubixGaid = 8,
  MubixDeviceId_FieldNumber_MubixMac = 9,
  MubixDeviceId_FieldNumber_MubixWifiMac = 10,
  MubixDeviceId_FieldNumber_MubixSsid = 11,
  MubixDeviceId_FieldNumber_MubixImsi = 12,
};

/**
 * 设备ID类信息
 **/
UbiX_GPB_FINAL @interface MubixDeviceId : UbiXGPBMessage

/** iOS必填。IOS为IDFA（明文，大写），带"-"，若取不到则传空值"" */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixIdfa;

/** iOS必填，若取不到则传空值"" */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixIdfv;

/** iOS选填 广协caid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixGxdi;

/** Android必填 设备IMEI（明文），Android必填，若取不到则传空值"". */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixImei;

/** Android必填 匿名设备标识符，原文 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixOaid;

/** Android必填 原文，明文 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixAid;

/** Android海外必填， 国内选填 原文，明文 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixGaid;

/** 设备的mac地址，原文 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixMac;

/** WIFI路由器MAC地址 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixWifiMac;

/** 无线网SSID名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixSsid;

/** IMSI（SIM卡串号） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixImsi;

@end

#pragma mark - MubixConfigResponse

typedef UbiX_GPB_ENUM(MubixConfigResponse_FieldNumber) {
  MubixConfigResponse_FieldNumber_MubixStatusCode = 1,
  MubixConfigResponse_FieldNumber_MubixIsTest = 2,
  MubixConfigResponse_FieldNumber_MubixStrategiesArray = 3,
  MubixConfigResponse_FieldNumber_MubixStrategyIsUpdate = 4,
  MubixConfigResponse_FieldNumber_MubixStrategyMd5Id = 5,
  MubixConfigResponse_FieldNumber_MubixTimestamp = 6,
  MubixConfigResponse_FieldNumber_MubixSlotId = 7,
};

UbiX_GPB_FINAL @interface MubixConfigResponse : UbiXGPBMessage

/** 状态码 */
@property(nonatomic, readwrite) int32_t mubixStatusCode;

/** 是否测试模式 */
@property(nonatomic, readwrite) BOOL mubixIsTest;

/** 策略模块 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MubixConfigResponse_MubixStrategy*> *mubixStrategiesArray;
/** The number of items in @c mubixStrategiesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger mubixStrategiesArray_Count;

/** 是否需要更新策略 */
@property(nonatomic, readwrite) BOOL mubixStrategyIsUpdate;

/** 策略的MD5唯一值 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixStrategyMd5Id;

/** 时间戳 */
@property(nonatomic, readwrite) int64_t mubixTimestamp;

/** 广告位id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixSlotId;

@end

#pragma mark - MubixConfigResponse_MubixStrategy

typedef UbiX_GPB_ENUM(MubixConfigResponse_MubixStrategy_FieldNumber) {
  MubixConfigResponse_MubixStrategy_FieldNumber_MubixMediationSlotId = 1,
  MubixConfigResponse_MubixStrategy_FieldNumber_MubixAdSourcesArray = 2,
  MubixConfigResponse_MubixStrategy_FieldNumber_MubixAdType = 4,
  MubixConfigResponse_MubixStrategy_FieldNumber_MubixStatus = 5,
  MubixConfigResponse_MubixStrategy_FieldNumber_MubixTotalTimeout = 12,
  MubixConfigResponse_MubixStrategy_FieldNumber_MubixWaterfallLayerTimeout = 13,
  MubixConfigResponse_MubixStrategy_FieldNumber_MubixBiddingTimeout = 14,
  MubixConfigResponse_MubixStrategy_FieldNumber_MubixStrategyId = 15,
  MubixConfigResponse_MubixStrategy_FieldNumber_MubixImpInterval = 16,
  MubixConfigResponse_MubixStrategy_FieldNumber_MubixBiddingFloor = 17,
  MubixConfigResponse_MubixStrategy_FieldNumber_MubixExt = 18,
  MubixConfigResponse_MubixStrategy_FieldNumber_MubixAdPreCache = 19,
  MubixConfigResponse_MubixStrategy_FieldNumber_MubixAdMarginRate = 20,
  MubixConfigResponse_MubixStrategy_FieldNumber_MubixAdContractType = 21,
  MubixConfigResponse_MubixStrategy_FieldNumber_MubixAdBidPrice = 22,
  MubixConfigResponse_MubixStrategy_FieldNumber_MubixMode = 23,
  MubixConfigResponse_MubixStrategy_FieldNumber_MubixAuditType = 24,
  MubixConfigResponse_MubixStrategy_FieldNumber_MubixIsNeedSend = 25,
  MubixConfigResponse_MubixStrategy_FieldNumber_MubixAdSourceWhitelist = 26,
  MubixConfigResponse_MubixStrategy_FieldNumber_MubixAdTypeWhitelist = 27,
  MubixConfigResponse_MubixStrategy_FieldNumber_MubixAbTest = 28,
  MubixConfigResponse_MubixStrategy_FieldNumber_MubixUseStrategyCache = 29,
  MubixConfigResponse_MubixStrategy_FieldNumber_MubixSdkAccessMode = 30,
  MubixConfigResponse_MubixStrategy_FieldNumber_ServerExtParams = 31,
  MubixConfigResponse_MubixStrategy_FieldNumber_MubixFallbackAdDelaytime = 32,
  MubixConfigResponse_MubixStrategy_FieldNumber_MubixAbtestGroupId = 33,
  MubixConfigResponse_MubixStrategy_FieldNumber_MubixAdAutoRefresh = 34,
  MubixConfigResponse_MubixStrategy_FieldNumber_MubixAdRefreshInterval = 35,
};

UbiX_GPB_FINAL @interface MubixConfigResponse_MubixStrategy : UbiXGPBMessage

/** mediation 广告位id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixMediationSlotId;

/** 广告平台列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MubixSdkConfig*> *mubixAdSourcesArray;
/** The number of items in @c mubixAdSourcesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger mubixAdSourcesArray_Count;

/** 广告类型 */
@property(nonatomic, readwrite) int32_t mubixAdType;

/** 聚合广告位状态 1 开启， 2 关闭 */
@property(nonatomic, readwrite) int32_t mubixStatus;

/**
 *    MubixBanner mubix_banner                           = 6;  //横幅相关参数
 *    MubixSplash mubix_splash                           = 7;  //开屏相关参数
 *    MubixNative mubix_native                           = 8;  //信息流相关参数
 *    MubixInterstitial mubix_interstitial               = 9;  //插屏相关参数
 *    MubixRewardVideo mubix_reward_video                = 10; //激励视频相关参数
 **/
@property(nonatomic, readwrite) int32_t mubixTotalTimeout;

/** 单次并发请求时间限制（单位ms） */
@property(nonatomic, readwrite) int32_t mubixWaterfallLayerTimeout;

/** 瀑布流单层超时时间（单位ms） */
@property(nonatomic, readwrite) int32_t mubixBiddingTimeout;

/** 流量组id */
@property(nonatomic, readwrite) int32_t mubixStrategyId;

/** 广告位曝光间隔（单位ms） */
@property(nonatomic, readwrite) int64_t mubixImpInterval;

/** bidding过滤底价（单位/分） */
@property(nonatomic, readwrite) int64_t mubixBiddingFloor;

/** 额外参数 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixExt;

/** 广告预缓存设置参数 */
@property(nonatomic, readwrite, strong, null_resettable) MubixConfigResponse_MubixStrategy_MubixAdPreCache *mubixAdPreCache;
/** Test to see if @c mubixAdPreCache has been set. */
@property(nonatomic, readwrite) BOOL hasMubixAdPreCache;

/** 利润率 */
@property(nonatomic, readwrite) int32_t mubixAdMarginRate;

/** 1=期望ECPM 2=bidding */
@property(nonatomic, readwrite) int32_t mubixAdContractType;

/** 期望ecpm */
@property(nonatomic, readwrite) int32_t mubixAdBidPrice;

/** 合作模式 1=分成 2=saas */
@property(nonatomic, readwrite) int32_t mubixMode;

/** 审核方式：1=免审；2=先审后投(默认)；3=先投后审(2.10.0删除) */
@property(nonatomic, readwrite) int32_t mubixAuditType;

/** audit_type=2时，是否需要媒体送审 0=不需要1=需要(默认)(2.10.0删除) */
@property(nonatomic, readwrite) int32_t mubixIsNeedSend;

/** 广告源白名单(2.10.0删除) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixAdSourceWhitelist;

/** 广告类型白名单(2.10.0删除) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixAdTypeWhitelist;

/** 服务端下发，AB实验ID。（预留字段，默认为空） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixAbTest;

/** 是否使用缓存的策略。 */
@property(nonatomic, readwrite) BOOL mubixUseStrategyCache;

/** SDK接入方式（竞价方式） 字典 1:客户端 2:服务端 */
@property(nonatomic, readwrite) int32_t mubixSdkAccessMode;

/** 非必填 服务端扩展参数，服务端下发后，端上无需关注具体字段随埋点上报，参数结构在mediation_server_ext_params.proto体现属于内部协议 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *serverExtParams;

/** 兜底广告延迟请求时间，单位：ms */
@property(nonatomic, readwrite) int64_t mubixFallbackAdDelaytime;

/** 服务端下发，AB实验用户分组ID。（预留字段，默认为空） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixAbtestGroupId;

/** 是否支持轮播，true：轮播，false：不轮播，目前仅支持banner样式。 */
@property(nonatomic, readwrite) BOOL mubixAdAutoRefresh;

/** 轮播间隔，10-200秒（默认30秒），目前仅支持banner样式。 */
@property(nonatomic, readwrite) int32_t mubixAdRefreshInterval;

@end

#pragma mark - MubixConfigResponse_MubixStrategy_MubixAdPreCache

typedef UbiX_GPB_ENUM(MubixConfigResponse_MubixStrategy_MubixAdPreCache_FieldNumber) {
  MubixConfigResponse_MubixStrategy_MubixAdPreCache_FieldNumber_MubixIsCacheFirst = 1,
  MubixConfigResponse_MubixStrategy_MubixAdPreCache_FieldNumber_MubixCacheLimitSize = 3,
  MubixConfigResponse_MubixStrategy_MubixAdPreCache_FieldNumber_MubixCacheExpireTime = 4,
  MubixConfigResponse_MubixStrategy_MubixAdPreCache_FieldNumber_MubixIsUseCache = 5,
};

UbiX_GPB_FINAL @interface MubixConfigResponse_MubixStrategy_MubixAdPreCache : UbiXGPBMessage

/** 必填.是否优先使用缓存，默认不优先使用。 1.使用 2 不使用 */
@property(nonatomic, readwrite) int32_t mubixIsCacheFirst;

/**        int64 mubix_request_wait_time = 2;  //请求等待时间，默认为3000 ms */
@property(nonatomic, readwrite) int32_t mubixCacheLimitSize;

/** 缓存广告的失效时间，默认30分钟 */
@property(nonatomic, readwrite) int32_t mubixCacheExpireTime;

/** 必填.是否使用缓存，默认使用。 1.使用 2 不使用 */
@property(nonatomic, readwrite) int32_t mubixIsUseCache;

@end

#pragma mark - MubixConfigResponse_MubixStrategy_MubixBanner

typedef UbiX_GPB_ENUM(MubixConfigResponse_MubixStrategy_MubixBanner_FieldNumber) {
  MubixConfigResponse_MubixStrategy_MubixBanner_FieldNumber_MubixRefresh = 1,
};

/**
 * 横幅
 **/
UbiX_GPB_FINAL @interface MubixConfigResponse_MubixStrategy_MubixBanner : UbiXGPBMessage

/** 横幅轮播刷新时间 */
@property(nonatomic, readwrite) int32_t mubixRefresh;

@end

#pragma mark - MubixConfigResponse_MubixStrategy_MubixSplash

/**
 * 开屏
 **/
UbiX_GPB_FINAL @interface MubixConfigResponse_MubixStrategy_MubixSplash : UbiXGPBMessage

@end

#pragma mark - MubixConfigResponse_MubixStrategy_MubixNative

/**
 * 信息流
 **/
UbiX_GPB_FINAL @interface MubixConfigResponse_MubixStrategy_MubixNative : UbiXGPBMessage

@end

#pragma mark - MubixConfigResponse_MubixStrategy_MubixInterstitial

/**
 * 插屏
 **/
UbiX_GPB_FINAL @interface MubixConfigResponse_MubixStrategy_MubixInterstitial : UbiXGPBMessage

@end

#pragma mark - MubixConfigResponse_MubixStrategy_MubixRewardVideo

/**
 * 激励视频
 **/
UbiX_GPB_FINAL @interface MubixConfigResponse_MubixStrategy_MubixRewardVideo : UbiXGPBMessage

@end

#pragma mark - MubixSdkConfig

typedef UbiX_GPB_ENUM(MubixSdkConfig_FieldNumber) {
  MubixSdkConfig_FieldNumber_MubixPlatformId = 1,
  MubixSdkConfig_FieldNumber_MubixAppId = 2,
  MubixSdkConfig_FieldNumber_MubixSlotId = 3,
  MubixSdkConfig_FieldNumber_MubixKeywords1 = 4,
  MubixSdkConfig_FieldNumber_MubixKeywords2 = 5,
  MubixSdkConfig_FieldNumber_MubixKeywords3 = 6,
  MubixSdkConfig_FieldNumber_MubixBidPrice = 8,
  MubixSdkConfig_FieldNumber_MubixRenderMethod = 9,
  MubixSdkConfig_FieldNumber_MubixBidType = 10,
  MubixSdkConfig_FieldNumber_MubixImpInterval = 11,
  MubixSdkConfig_FieldNumber_MubixExt = 12,
  MubixSdkConfig_FieldNumber_MubixFloorIndex = 13,
  MubixSdkConfig_FieldNumber_MubixAuditType = 14,
  MubixSdkConfig_FieldNumber_MubixFloorTimeout = 15,
  MubixSdkConfig_FieldNumber_MubixSdkAccessMode = 16,
  MubixSdkConfig_FieldNumber_MubixManagerPlatformId = 17,
  MubixSdkConfig_FieldNumber_MubixShakingConfig = 18,
};

UbiX_GPB_FINAL @interface MubixSdkConfig : UbiXGPBMessage

/**
 *  enum Platform {
 *    UNKOWN         = 0; //未知
 *    PANGLE         = 1; //穿山甲
 *    GDT            = 2; //优量汇
 *    KUAISHOU       = 3; //快手
 *    JINGMEI        = 4; //京媒
 *    UBIX           = 5; //UBiX
 *    BAIDU          = 6; //百度
 *    IQIYI          = 7; //爱奇艺
 *    SIGMOB         = 8; //Sigmob
 *    HUAWEI         = 9; //华为
 *    ADHUB          = 10; //adhub
 *  }
 **/
@property(nonatomic, readwrite) int32_t mubixPlatformId;

/** app id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixAppId;

/** slot id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixSlotId;

/** 扩展字段1 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixKeywords1;

/** 扩展字段2 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixKeywords2;

/** 扩展字段3 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixKeywords3;

/** 预估出价 - 只对waterfall形式时下发 单位:分 */
@property(nonatomic, readwrite) int64_t mubixBidPrice;

/** 渲染方式 1:自渲染 2:模版渲染 */
@property(nonatomic, readwrite) int32_t mubixRenderMethod;

/** 竞价类型 0-waterfall, 1-bidding */
@property(nonatomic, readwrite) int32_t mubixBidType;

/** 针对该平台广告的曝光间隔（单位ms），大于0为有效值，等于0代表不对曝光间隔进行限制 */
@property(nonatomic, readwrite) int64_t mubixImpInterval;

/** 通用扩展字段，由客户端解析 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixExt;

/** 广告源所属的转发层级 */
@property(nonatomic, readwrite) int32_t mubixFloorIndex;

/** 广告源是否需要审核 */
@property(nonatomic, readwrite) BOOL mubixAuditType;

/** 广告源所属的转发层级的单层超时时间（单位ms） */
@property(nonatomic, readwrite) int32_t mubixFloorTimeout;

/** SDK接入方式（竞价方式） 字典 1:客户端 2:服务端 */
@property(nonatomic, readwrite) int32_t mubixSdkAccessMode;

/** 管理平台枚举值 */
@property(nonatomic, readwrite) int32_t mubixManagerPlatformId;

/** 摇一摇配置 */
@property(nonatomic, readwrite, strong, null_resettable) MubixSdkConfig_ShakingConfig *mubixShakingConfig;
/** Test to see if @c mubixShakingConfig has been set. */
@property(nonatomic, readwrite) BOOL hasMubixShakingConfig;

@end

#pragma mark - MubixSdkConfig_ShakingConfig

typedef UbiX_GPB_ENUM(MubixSdkConfig_ShakingConfig_FieldNumber) {
  MubixSdkConfig_ShakingConfig_FieldNumber_MubixEnabled = 1,
  MubixSdkConfig_ShakingConfig_FieldNumber_MubixImgW = 2,
  MubixSdkConfig_ShakingConfig_FieldNumber_MubixImgH = 3,
};

/**
 * ShakingConfig 摇一摇配置
 **/
UbiX_GPB_FINAL @interface MubixSdkConfig_ShakingConfig : UbiXGPBMessage

/** 自渲染开启摇一摇 */
@property(nonatomic, readwrite) BOOL mubixEnabled;

/** 摇一摇图片宽，单位（像素） */
@property(nonatomic, readwrite) uint32_t mubixImgW;

/** 摇一摇图片高，单位（像素） */
@property(nonatomic, readwrite) uint32_t mubixImgH;

@end

#pragma mark - UBixMaterialWlistRequest

typedef UbiX_GPB_ENUM(UBixMaterialWlistRequest_FieldNumber) {
  UBixMaterialWlistRequest_FieldNumber_SdkVersion = 1,
  UBixMaterialWlistRequest_FieldNumber_AppId = 2,
};

/**
 * 聚合素材白名单接口请求格式(2.11.0 废弃)
 **/
UbiX_GPB_FINAL @interface UBixMaterialWlistRequest : UbiXGPBMessage

/** sdk版本 格式如：1.0.1 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sdkVersion;

/** 聚合应用id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *appId;

@end

#pragma mark - UBixMaterialHlistRequest

typedef UbiX_GPB_ENUM(UBixMaterialHlistRequest_FieldNumber) {
  UBixMaterialHlistRequest_FieldNumber_SdkVersion = 1,
  UBixMaterialHlistRequest_FieldNumber_AppId = 2,
};

/**
 * 聚合素材黑名单名单接口请求格式(2.11.废弃)
 **/
UbiX_GPB_FINAL @interface UBixMaterialHlistRequest : UbiXGPBMessage

/** sdk版本 格式如：1.0.1 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sdkVersion;

/** 聚合应用id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *appId;

@end

#pragma mark - UBixMaterialWlistResponse

typedef UbiX_GPB_ENUM(UBixMaterialWlistResponse_FieldNumber) {
  UBixMaterialWlistResponse_FieldNumber_Status = 1,
  UBixMaterialWlistResponse_FieldNumber_Materials = 2,
};

/**
 * 聚合素材白名单接口返回格式(2.11.0 废弃)
 **/
UbiX_GPB_FINAL @interface UBixMaterialWlistResponse : UbiXGPBMessage

/** 0代表成功，非0的代表失败 */
@property(nonatomic, readwrite) int32_t status;

/** 素材md5为 k, 审核状态为 v。 当前版本先不用考虑int状态 */
@property(nonatomic, readwrite, strong, null_resettable) UbiXGPBStringInt32Dictionary *materials;
/** The number of items in @c materials without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger materials_Count;

@end

#pragma mark - UBixMaterialRealtimeRequest

typedef UbiX_GPB_ENUM(UBixMaterialRealtimeRequest_FieldNumber) {
  UBixMaterialRealtimeRequest_FieldNumber_SdkVersion = 1,
  UBixMaterialRealtimeRequest_FieldNumber_AppId = 2,
  UBixMaterialRealtimeRequest_FieldNumber_AdType = 3,
  UBixMaterialRealtimeRequest_FieldNumber_URL = 4,
  UBixMaterialRealtimeRequest_FieldNumber_Title = 5,
  UBixMaterialRealtimeRequest_FieldNumber_Desc = 6,
  UBixMaterialRealtimeRequest_FieldNumber_Md5 = 7,
  UBixMaterialRealtimeRequest_FieldNumber_MubixReviewId = 8,
  UBixMaterialRealtimeRequest_FieldNumber_MubixMaterialId = 9,
  UBixMaterialRealtimeRequest_FieldNumber_MubixSecondVerify = 10,
};

/**
 * 聚合素材实时接口请求格式（端上2.11.0 废弃）
 **/
UbiX_GPB_FINAL @interface UBixMaterialRealtimeRequest : UbiXGPBMessage

/** sdk版本 格式如：1.0.1 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sdkVersion;

/** 聚合应用id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *appId;

/** 广告类型 */
@property(nonatomic, readwrite) int32_t adType;

/** 素材地址, 多图按顺序逗号隔开（2.10.0删除） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

/** 标题 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

/** 描述 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *desc;

/** 图片文件md5值（2.10.0删除） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *md5;

/** 素材审核规则id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixReviewId;

/** 素材id，逗号分隔。 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixMaterialId;

/** 先审后投命中免审并开启先验设置为true，其他情况false； */
@property(nonatomic, readwrite) BOOL mubixSecondVerify;

@end

#pragma mark - UBixMaterialRealtimeResponse

typedef UbiX_GPB_ENUM(UBixMaterialRealtimeResponse_FieldNumber) {
  UBixMaterialRealtimeResponse_FieldNumber_Status = 1,
};

/**
 * 聚合素材实时接口返回格式（端上2.11.0废弃）
 **/
UbiX_GPB_FINAL @interface UBixMaterialRealtimeResponse : UbiXGPBMessage

/** 1=可投，2=不可投 */
@property(nonatomic, readwrite) int32_t status;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
