// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mdnow/mediation_app_api.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(UbiX_GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define UbiX_GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if UbiX_GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/UbiXGPBProtocolBuffers.h>
#else
 #import <UbiXDaq/UbiXGPBProtocolBuffers.h>
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class MUBiXMaterialBlock;
@class MUBiXMaterialModule;
@class MUbixAdConfigResponseInfo;
@class MUbixInitResponse;
@class MubixConfigRequest_MubixAppInfo;
@class MubixConfigRequest_MubixDeviceInfo;
@class MubixConfigRequest_MubixMediationSlot;
@class MubixConfigRequest_MubixUserInfo;
@class MubixConfigResponse;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MediationAppApiRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (UbiXGPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c UbiXGPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
UbiX_GPB_FINAL @interface MediationAppApiRoot : UbiXGPBRootObject
@end

#pragma mark - MUbixAppConfigRequest

typedef UbiX_GPB_ENUM(MUbixAppConfigRequest_FieldNumber) {
  MUbixAppConfigRequest_FieldNumber_MubixSdkVersion = 1,
  MUbixAppConfigRequest_FieldNumber_MubixApp = 2,
  MUbixAppConfigRequest_FieldNumber_MubixDevice = 3,
  MUbixAppConfigRequest_FieldNumber_MubixConfigType = 4,
  MUbixAppConfigRequest_FieldNumber_MubixTimestamp = 5,
  MUbixAppConfigRequest_FieldNumber_MubixMediationSlotArray = 6,
  MUbixAppConfigRequest_FieldNumber_MubixLogReady = 7,
  MUbixAppConfigRequest_FieldNumber_MubixInstalledAppsArray = 8,
  MUbixAppConfigRequest_FieldNumber_MubixUserInfo = 9,
  MUbixAppConfigRequest_FieldNumber_MubixInitResponseMd5 = 10,
  MUbixAppConfigRequest_FieldNumber_MubixMaterialMd5 = 11,
};

UbiX_GPB_FINAL @interface MUbixAppConfigRequest : UbiXGPBMessage

/** 必填。当前sdk的版本。格式如：1.0.0 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixSdkVersion;

/** 必填。移动app的信息。 */
@property(nonatomic, readwrite, strong, null_resettable) MubixConfigRequest_MubixAppInfo *mubixApp;
/** Test to see if @c mubixApp has been set. */
@property(nonatomic, readwrite) BOOL hasMubixApp;

/** 必填。移动设备的信息。 */
@property(nonatomic, readwrite, strong, null_resettable) MubixConfigRequest_MubixDeviceInfo *mubixDevice;
/** Test to see if @c mubixDevice has been set. */
@property(nonatomic, readwrite) BOOL hasMubixDevice;

/** 1:全量下发配置， 2:下发单个广告位（不下发云控配置）3: 只刷新初始化 */
@property(nonatomic, readwrite) int32_t mubixConfigType;

/** 触发时间 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixTimestamp;

/** 聚合广告位列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MubixConfigRequest_MubixMediationSlot*> *mubixMediationSlotArray;
/** The number of items in @c mubixMediationSlotArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger mubixMediationSlotArray_Count;

/** false: 无错误日志, true: 存在错误日志 */
@property(nonatomic, readwrite) BOOL mubixLogReady;

/** 获得的安装的应用ID列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *mubixInstalledAppsArray;
/** The number of items in @c mubixInstalledAppsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger mubixInstalledAppsArray_Count;

/** 用户信息 */
@property(nonatomic, readwrite, strong, null_resettable) MubixConfigRequest_MubixUserInfo *mubixUserInfo;
/** Test to see if @c mubixUserInfo has been set. */
@property(nonatomic, readwrite) BOOL hasMubixUserInfo;

/** 初始化信息 md5 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixInitResponseMd5;

/** 素材屏蔽md5 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixMaterialMd5;

@end

#pragma mark - MUbixAppConfigResponse

typedef UbiX_GPB_ENUM(MUbixAppConfigResponse_FieldNumber) {
  MUbixAppConfigResponse_FieldNumber_MubixInitResponse = 1,
  MUbixAppConfigResponse_FieldNumber_MubixConfigResponseInfo = 2,
  MUbixAppConfigResponse_FieldNumber_MubixTimestamp = 3,
  MUbixAppConfigResponse_FieldNumber_MubixMaterialModule = 4,
};

UbiX_GPB_FINAL @interface MUbixAppConfigResponse : UbiXGPBMessage

/** 初始化信息 */
@property(nonatomic, readwrite, strong, null_resettable) MUbixInitResponse *mubixInitResponse;
/** Test to see if @c mubixInitResponse has been set. */
@property(nonatomic, readwrite) BOOL hasMubixInitResponse;

/** 策略返回 */
@property(nonatomic, readwrite, strong, null_resettable) MUbixAdConfigResponseInfo *mubixConfigResponseInfo;
/** Test to see if @c mubixConfigResponseInfo has been set. */
@property(nonatomic, readwrite) BOOL hasMubixConfigResponseInfo;

/** 时间戳 */
@property(nonatomic, readwrite) int64_t mubixTimestamp;

/** 素材屏蔽模块。 */
@property(nonatomic, readwrite, strong, null_resettable) MUBiXMaterialModule *mubixMaterialModule;
/** Test to see if @c mubixMaterialModule has been set. */
@property(nonatomic, readwrite) BOOL hasMubixMaterialModule;

@end

#pragma mark - MUbixAdConfigResponseInfo

typedef UbiX_GPB_ENUM(MUbixAdConfigResponseInfo_FieldNumber) {
  MUbixAdConfigResponseInfo_FieldNumber_MubixStatusCode = 1,
  MUbixAdConfigResponseInfo_FieldNumber_MubixConfigResponseListArray = 2,
};

UbiX_GPB_FINAL @interface MUbixAdConfigResponseInfo : UbiXGPBMessage

/** 状态码 */
@property(nonatomic, readwrite) int32_t mubixStatusCode;

/** 策略列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MubixConfigResponse*> *mubixConfigResponseListArray;
/** The number of items in @c mubixConfigResponseListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger mubixConfigResponseListArray_Count;

@end

#pragma mark - MUBiXMaterialModule

typedef UbiX_GPB_ENUM(MUBiXMaterialModule_FieldNumber) {
  MUBiXMaterialModule_FieldNumber_MubixStatusCode = 1,
  MUBiXMaterialModule_FieldNumber_MubixBlockContentArray = 2,
  MUBiXMaterialModule_FieldNumber_MubixIsUpdate = 3,
  MUBiXMaterialModule_FieldNumber_MubixMaterialMd5 = 4,
};

/**
 * 素材屏蔽模块
 **/
UbiX_GPB_FINAL @interface MUBiXMaterialModule : UbiXGPBMessage

/** 状态码,1：有屏蔽规则 ；2:没有屏蔽规则 */
@property(nonatomic, readwrite) int32_t mubixStatusCode;

/** 素材屏蔽的内容 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MUBiXMaterialBlock*> *mubixBlockContentArray;
/** The number of items in @c mubixBlockContentArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger mubixBlockContentArray_Count;

/** 是否更新本地素材屏蔽规则。 */
@property(nonatomic, readwrite) BOOL mubixIsUpdate;

/** 素材屏蔽md5 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixMaterialMd5;

@end

#pragma mark - MUBiXMaterialBlock

typedef UbiX_GPB_ENUM(MUBiXMaterialBlock_FieldNumber) {
  MUBiXMaterialBlock_FieldNumber_MubixSlotIdArray = 1,
  MUBiXMaterialBlock_FieldNumber_MubixKeywordsArray = 2,
  MUBiXMaterialBlock_FieldNumber_MubixMaterialURLArray = 3,
  MUBiXMaterialBlock_FieldNumber_MubixBlockId = 4,
  MUBiXMaterialBlock_FieldNumber_MubixTargetURLProtocolArray = 5,
  MUBiXMaterialBlock_FieldNumber_MubixTargetURLDomainArray = 6,
  MUBiXMaterialBlock_FieldNumber_MubixPackageNameArray = 7,
  MUBiXMaterialBlock_FieldNumber_MubixAppId = 8,
};

UbiX_GPB_FINAL @interface MUBiXMaterialBlock : UbiXGPBMessage

/** 广告位 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *mubixSlotIdArray;
/** The number of items in @c mubixSlotIdArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger mubixSlotIdArray_Count;

/** 关键词 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *mubixKeywordsArray;
/** The number of items in @c mubixKeywordsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger mubixKeywordsArray_Count;

/** 素材域名 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *mubixMaterialURLArray;
/** The number of items in @c mubixMaterialURLArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger mubixMaterialURLArray_Count;

/** 屏蔽规则id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixBlockId;

/** 落地页协议头 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *mubixTargetURLProtocolArray;
/** The number of items in @c mubixTargetURLProtocolArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger mubixTargetURLProtocolArray_Count;

/** 落地页域名 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *mubixTargetURLDomainArray;
/** The number of items in @c mubixTargetURLDomainArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger mubixTargetURLDomainArray_Count;

/** 预算包名 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *mubixPackageNameArray;
/** The number of items in @c mubixPackageNameArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger mubixPackageNameArray_Count;

/** 应用id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixAppId;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
