// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mediation_init_api.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(UbiX_GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define UbiX_GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if UbiX_GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/UbiXGPBProtocolBuffers.h>
#else
#import <UbiXDaq/UbiXGPBProtocolBuffers.h>
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class MUbixCollectModule;
@class MUbixCollectModule_MUbixMode;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MediationInitApiRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (UbiXGPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c UbiXGPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
UbiX_GPB_FINAL @interface MediationInitApiRoot : UbiXGPBRootObject
@end

#pragma mark - MUbixInitResponse

typedef UbiX_GPB_ENUM(MUbixInitResponse_FieldNumber) {
  MUbixInitResponse_FieldNumber_MubixStatus = 1,
  MUbixInitResponse_FieldNumber_MubixCollectModule = 2,
  MUbixInitResponse_FieldNumber_MubixDebug = 3,
  MUbixInitResponse_FieldNumber_MubixInitInterval = 4,
  MUbixInitResponse_FieldNumber_MubixScanApp = 5,
  MUbixInitResponse_FieldNumber_MubixScanAppInterval = 6,
  MUbixInitResponse_FieldNumber_MubixParamInterval = 7,
  MUbixInitResponse_FieldNumber_MubixAppPkgDict = 8,
  MUbixInitResponse_FieldNumber_MubixAppSchemeDict = 9,
  MUbixInitResponse_FieldNumber_MubixBackupDomainsArray = 10,
  MUbixInitResponse_FieldNumber_MubixNeedTrackingStatusCodeArray = 11,
  MUbixInitResponse_FieldNumber_MubixCloseLocation = 12,
  MUbixInitResponse_FieldNumber_MubixClosePhoneState = 13,
  MUbixInitResponse_FieldNumber_MubixCloseWifiState = 14,
  MUbixInitResponse_FieldNumber_MubixCloseAndroidId = 15,
  MUbixInitResponse_FieldNumber_MubixCloseOaid = 16,
  MUbixInitResponse_FieldNumber_MubixCloseWriteExternal = 17,
  MUbixInitResponse_FieldNumber_MubixCloseMacAddress = 18,
  MUbixInitResponse_FieldNumber_MubixCloseIdfa = 19,
  MUbixInitResponse_FieldNumber_MubixExt = 20,
  MUbixInitResponse_FieldNumber_MubixCacheSize = 21,
  MUbixInitResponse_FieldNumber_MubixCacheExpireTime = 22,
  MUbixInitResponse_FieldNumber_MubixMonitorCacheInterval = 23,
  MUbixInitResponse_FieldNumber_MubixStrategyCacheExpireTime = 24,
  MUbixInitResponse_FieldNumber_MubixRequestStrategyInterval = 25,
  MUbixInitResponse_FieldNumber_MubixScanType = 26,
  MUbixInitResponse_FieldNumber_MubixStatusCode = 27,
  MUbixInitResponse_FieldNumber_MubixTimestamp = 28,
  MUbixInitResponse_FieldNumber_MubixServerRequestStrategyInterval = 29,
  MUbixInitResponse_FieldNumber_MubixMaterialBackupDomainsArray = 30,
  MUbixInitResponse_FieldNumber_MubixAppStatus = 31,
  MUbixInitResponse_FieldNumber_MubixResponseMd5 = 33,
  MUbixInitResponse_FieldNumber_MubixIsUpdate = 34,
  MUbixInitResponse_FieldNumber_MubixUb = 35,
  MUbixInitResponse_FieldNumber_MubixSm = 36,
  MUbixInitResponse_FieldNumber_MubixPT = 37,
};

UbiX_GPB_FINAL @interface MUbixInitResponse : UbiXGPBMessage

/** 聚合SDK-状态 1 开启， 2 关闭 */
@property(nonatomic, readwrite) int32_t mubixStatus;

/** 采集模块 */
@property(nonatomic, readwrite, strong, null_resettable) MUbixCollectModule *mubixCollectModule;
/** Test to see if @c mubixCollectModule has been set. */
@property(nonatomic, readwrite) BOOL hasMubixCollectModule;

/** 是否需要上传错误日志 */
@property(nonatomic, readwrite) BOOL mubixDebug;

/** 初始化时间间隔, 默认缺省值: 600 (=10分钟)， 单位:s */
@property(nonatomic, readwrite) int32_t mubixInitInterval;

/** 是否允许扫包 */
@property(nonatomic, readwrite) BOOL mubixScanApp;

/** 扫描应用包间隔 */
@property(nonatomic, readwrite) int32_t mubixScanAppInterval;

/** 获取系统参数间隔, 默认缺省值: 10, 单位: s */
@property(nonatomic, readwrite) int32_t mubixParamInterval;

/** 需要进行安装检查的包名到安装的应用ID字典 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *mubixAppPkgDict;
/** The number of items in @c mubixAppPkgDict without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger mubixAppPkgDict_Count;

/** 需要检查的scheme调起链接前缀到安装的应用ID字典 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *mubixAppSchemeDict;
/** The number of items in @c mubixAppSchemeDict without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger mubixAppSchemeDict_Count;

/** 聚合服务备用域名 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *mubixBackupDomainsArray;
/** The number of items in @c mubixBackupDomainsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger mubixBackupDomainsArray_Count;

/** 需要上报的埋点数组 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *mubixNeedTrackingStatusCodeArray;
/** The number of items in @c mubixNeedTrackingStatusCodeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger mubixNeedTrackingStatusCodeArray_Count;

/** 是否关闭获取位置信息 */
@property(nonatomic, readwrite) BOOL mubixCloseLocation;

/** 是否关闭获取手机信息 如imei imsi */
@property(nonatomic, readwrite) BOOL mubixClosePhoneState;

/** 是否关闭获取wifi 状态信息 */
@property(nonatomic, readwrite) BOOL mubixCloseWifiState;

/** 是否关闭获取android id */
@property(nonatomic, readwrite) BOOL mubixCloseAndroidId;

/** 是否关闭获取oaid */
@property(nonatomic, readwrite) BOOL mubixCloseOaid;

/** 是否关闭获取存储卡权限 */
@property(nonatomic, readwrite) BOOL mubixCloseWriteExternal;

/** 是否关闭获取mac 地址 */
@property(nonatomic, readwrite) BOOL mubixCloseMacAddress;

/** 是否关闭获取idfa */
@property(nonatomic, readwrite) BOOL mubixCloseIdfa;

/** 通用扩展字段，json格式，由客户端解析 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixExt;

/** 全部广告缓存最大个数 */
@property(nonatomic, readwrite) int32_t mubixCacheSize;

/** 缓存广告的失效时间，默认30分钟 */
@property(nonatomic, readwrite) int32_t mubixCacheExpireTime;

/** 监控缓存池个数的时间间隔，默认600秒 */
@property(nonatomic, readwrite) int32_t mubixMonitorCacheInterval;

/** 策略缓存有效期，单位分钟，默认 0 */
@property(nonatomic, readwrite) int32_t mubixStrategyCacheExpireTime;

/** 请求策略的时间间隔，单位分钟，默认 0 */
@property(nonatomic, readwrite) int32_t mubixRequestStrategyInterval;

/** 扫包类型，1:应用包名嗅探(安卓)、2:Deeplink嗅探(安卓\\iOS) */
@property(nonatomic, readwrite) int32_t mubixScanType;

/** 状态码 0-正常 非0-异常对应问题的状态码 */
@property(nonatomic, readwrite) int32_t mubixStatusCode;

/** 时间戳 */
@property(nonatomic, readwrite) int64_t mubixTimestamp;

/** serverbidding 请求策略的时间间隔，单位分钟，默认 0 */
@property(nonatomic, readwrite) int32_t mubixServerRequestStrategyInterval;

/** 素材备用域名 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *mubixMaterialBackupDomainsArray;
/** The number of items in @c mubixMaterialBackupDomainsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger mubixMaterialBackupDomainsArray_Count;

/** 应用状态 0-有效 1-无效 */
@property(nonatomic, readwrite) int32_t mubixAppStatus;

/** bool  mubix_material_rule_enabled              = 32;  // 素材规则是否生效。 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixResponseMd5;

/** 初始化配置是否变更 */
@property(nonatomic, readwrite) BOOL mubixIsUpdate;

/** 是否监测USB调试，1=不监测(默认)、2=监测、3=监测+拦截, 仅Android */
@property(nonatomic, readwrite) int32_t mubixUb;

/** 是否监测SIM卡，1=不监测(默认)、2=监测、3=监测+拦截,Android+iOS */
@property(nonatomic, readwrite) int32_t mubixSm;

/** protect_time，新安装设备拦截时间阈值，单位秒, “0”代表不设置拦截，未设值则端上使用默认值3天，Android+iOS */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mubixPT;

@end

#pragma mark - MUbixCollectModule

typedef UbiX_GPB_ENUM(MUbixCollectModule_FieldNumber) {
  MUbixCollectModule_FieldNumber_MubixStatus = 1,
  MUbixCollectModule_FieldNumber_MubixMode = 2,
  MUbixCollectModule_FieldNumber_MubixBackupDomainsArray = 3,
};

/**
 * 采集模块
 **/
UbiX_GPB_FINAL @interface MUbixCollectModule : UbiXGPBMessage

/** 状态 1 开启， 2 关闭 */
@property(nonatomic, readwrite) int32_t mubixStatus;

/** 采集模式 */
@property(nonatomic, readwrite, strong, null_resettable) MUbixCollectModule_MUbixMode *mubixMode;
/** Test to see if @c mubixMode has been set. */
@property(nonatomic, readwrite) BOOL hasMubixMode;

/** 采集服务备用域名 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *mubixBackupDomainsArray;
/** The number of items in @c mubixBackupDomainsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger mubixBackupDomainsArray_Count;

@end

#pragma mark - MUbixCollectModule_MUbixMode

typedef UbiX_GPB_ENUM(MUbixCollectModule_MUbixMode_FieldNumber) {
  MUbixCollectModule_MUbixMode_FieldNumber_MubixInterval = 1,
  MUbixCollectModule_MUbixMode_FieldNumber_MubixBatchSize = 2,
};

UbiX_GPB_FINAL @interface MUbixCollectModule_MUbixMode : UbiXGPBMessage

/** 定时周期  单位：秒， 默认15秒 */
@property(nonatomic, readwrite) int32_t mubixInterval;

/** 一次批量上报事件上限 */
@property(nonatomic, readwrite) int32_t mubixBatchSize;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
