// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/type.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(UbiX_GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define UbiX_GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if UbiX_GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/UbiXGPBDescriptor.h>
 #import <Protobuf/UbiXGPBMessage.h>
 #import <Protobuf/UbiXGPBRootObject.h>
#else
 #import "UbiXGPBDescriptor.h"
 #import "UbiXGPBMessage.h"
 #import "UbiXGPBRootObject.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class UbiXGPBAny;
@class UbiXGPBEnumValue;
@class UbiXGPBField;
@class UbiXGPBOption;
@class UbiXGPBSourceContext;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum UbiXGPBSyntax

/** The syntax in which a protocol buffer element is defined. */
typedef UbiX_GPB_ENUM(UbiXGPBSyntax) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  UbiXGPBSyntax_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** Syntax `proto2`. */
  UbiXGPBSyntax_SyntaxProto2 = 0,

  /** Syntax `proto3`. */
  UbiXGPBSyntax_SyntaxProto3 = 1,
};

UbiXGPBEnumDescriptor *UbiXGPBSyntax_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL UbiXGPBSyntax_IsValidValue(int32_t value);

#pragma mark - Enum UbiXGPBField_Kind

/** Basic field types. */
typedef UbiX_GPB_ENUM(UbiXGPBField_Kind) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  UbiXGPBField_Kind_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** Field type unknown. */
  UbiXGPBField_Kind_TypeUnknown = 0,

  /** Field type double. */
  UbiXGPBField_Kind_TypeDouble = 1,

  /** Field type float. */
  UbiXGPBField_Kind_TypeFloat = 2,

  /** Field type int64. */
  UbiXGPBField_Kind_TypeInt64 = 3,

  /** Field type uint64. */
  UbiXGPBField_Kind_TypeUint64 = 4,

  /** Field type int32. */
  UbiXGPBField_Kind_TypeInt32 = 5,

  /** Field type fixed64. */
  UbiXGPBField_Kind_TypeFixed64 = 6,

  /** Field type fixed32. */
  UbiXGPBField_Kind_TypeFixed32 = 7,

  /** Field type bool. */
  UbiXGPBField_Kind_TypeBool = 8,

  /** Field type string. */
  UbiXGPBField_Kind_TypeString = 9,

  /** Field type group. Proto2 syntax only, and deprecated. */
  UbiXGPBField_Kind_TypeGroup = 10,

  /** Field type message. */
  UbiXGPBField_Kind_TypeMessage = 11,

  /** Field type bytes. */
  UbiXGPBField_Kind_TypeBytes = 12,

  /** Field type uint32. */
  UbiXGPBField_Kind_TypeUint32 = 13,

  /** Field type enum. */
  UbiXGPBField_Kind_TypeEnum = 14,

  /** Field type sfixed32. */
  UbiXGPBField_Kind_TypeSfixed32 = 15,

  /** Field type sfixed64. */
  UbiXGPBField_Kind_TypeSfixed64 = 16,

  /** Field type sint32. */
  UbiXGPBField_Kind_TypeSint32 = 17,

  /** Field type sint64. */
  UbiXGPBField_Kind_TypeSint64 = 18,
};

UbiXGPBEnumDescriptor *UbiXGPBField_Kind_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL UbiXGPBField_Kind_IsValidValue(int32_t value);

#pragma mark - Enum UbiXGPBField_Cardinality

/** Whether a field is optional, required, or repeated. */
typedef UbiX_GPB_ENUM(UbiXGPBField_Cardinality) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  UbiXGPBField_Cardinality_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** For fields with unknown cardinality. */
  UbiXGPBField_Cardinality_CardinalityUnknown = 0,

  /** For optional fields. */
  UbiXGPBField_Cardinality_CardinalityOptional = 1,

  /** For required fields. Proto2 syntax only. */
  UbiXGPBField_Cardinality_CardinalityRequired = 2,

  /** For repeated fields. */
  UbiXGPBField_Cardinality_CardinalityRepeated = 3,
};

UbiXGPBEnumDescriptor *UbiXGPBField_Cardinality_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL UbiXGPBField_Cardinality_IsValidValue(int32_t value);

#pragma mark - UbiXGPBTypeRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (UbiXGPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c UbiXGPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
UbiX_GPB_FINAL @interface UbiXGPBTypeRoot : UbiXGPBRootObject
@end

#pragma mark - UbiXGPBType

typedef UbiX_GPB_ENUM(UbiXGPBType_FieldNumber) {
  UbiXGPBType_FieldNumber_Name = 1,
  UbiXGPBType_FieldNumber_FieldsArray = 2,
  UbiXGPBType_FieldNumber_OneofsArray = 3,
  UbiXGPBType_FieldNumber_OptionsArray = 4,
  UbiXGPBType_FieldNumber_SourceContext = 5,
  UbiXGPBType_FieldNumber_Syntax = 6,
};

/**
 * A protocol buffer message type.
 **/
UbiX_GPB_FINAL @interface UbiXGPBType : UbiXGPBMessage

/** The fully qualified message name. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** The list of fields. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UbiXGPBField*> *fieldsArray;
/** The number of items in @c fieldsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger fieldsArray_Count;

/** The list of types appearing in `oneof` definitions in this type. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *oneofsArray;
/** The number of items in @c oneofsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger oneofsArray_Count;

/** The protocol buffer options. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UbiXGPBOption*> *optionsArray;
/** The number of items in @c optionsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger optionsArray_Count;

/** The source context. */
@property(nonatomic, readwrite, strong, null_resettable) UbiXGPBSourceContext *sourceContext;
/** Test to see if @c sourceContext has been set. */
@property(nonatomic, readwrite) BOOL hasSourceContext;

/** The source syntax. */
@property(nonatomic, readwrite) UbiXGPBSyntax syntax;

@end

/**
 * Fetches the raw value of a @c UbiXGPBType's @c syntax property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t UbiXGPBType_Syntax_RawValue(UbiXGPBType *message);
/**
 * Sets the raw value of an @c UbiXGPBType's @c syntax property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void UbiXSetGPBType_Syntax_RawValue(UbiXGPBType *message, int32_t value);

#pragma mark - UbiXGPBField

typedef UbiX_GPB_ENUM(UbiXGPBField_FieldNumber) {
  UbiXGPBField_FieldNumber_Kind = 1,
  UbiXGPBField_FieldNumber_Cardinality = 2,
  UbiXGPBField_FieldNumber_Number = 3,
  UbiXGPBField_FieldNumber_Name = 4,
  UbiXGPBField_FieldNumber_TypeURL = 6,
  UbiXGPBField_FieldNumber_OneofIndex = 7,
  UbiXGPBField_FieldNumber_Packed = 8,
  UbiXGPBField_FieldNumber_OptionsArray = 9,
  UbiXGPBField_FieldNumber_JsonName = 10,
  UbiXGPBField_FieldNumber_DefaultValue = 11,
};

/**
 * A single field of a message type.
 **/
UbiX_GPB_FINAL @interface UbiXGPBField : UbiXGPBMessage

/** The field type. */
@property(nonatomic, readwrite) UbiXGPBField_Kind kind;

/** The field cardinality. */
@property(nonatomic, readwrite) UbiXGPBField_Cardinality cardinality;

/** The field number. */
@property(nonatomic, readwrite) int32_t number;

/** The field name. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/**
 * The field type URL, without the scheme, for message or enumeration
 * types. Example: `"type.googleapis.com/google.protobuf.Timestamp"`.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *typeURL;

/**
 * The index of the field type in `Type.oneofs`, for message or enumeration
 * types. The first type has index 1; zero means the type is not in the list.
 **/
@property(nonatomic, readwrite) int32_t oneofIndex;

/** Whether to use alternative packed wire representation. */
@property(nonatomic, readwrite) BOOL packed;

/** The protocol buffer options. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UbiXGPBOption*> *optionsArray;
/** The number of items in @c optionsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger optionsArray_Count;

/** The field JSON name. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *jsonName;

/** The string value of the default value of this field. Proto2 syntax only. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *defaultValue;

@end

/**
 * Fetches the raw value of a @c UbiXGPBField's @c kind property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t UbiXGPBField_Kind_RawValue(UbiXGPBField *message);
/**
 * Sets the raw value of an @c UbiXGPBField's @c kind property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void UbiXSetGPBField_Kind_RawValue(UbiXGPBField *message, int32_t value);

/**
 * Fetches the raw value of a @c UbiXGPBField's @c cardinality property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t UbiXGPBField_Cardinality_RawValue(UbiXGPBField *message);
/**
 * Sets the raw value of an @c UbiXGPBField's @c cardinality property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void UbiXSetGPBField_Cardinality_RawValue(UbiXGPBField *message, int32_t value);

#pragma mark - UbiXGPBEnum

typedef UbiX_GPB_ENUM(UbiXGPBEnum_FieldNumber) {
  UbiXGPBEnum_FieldNumber_Name = 1,
  UbiXGPBEnum_FieldNumber_EnumvalueArray = 2,
  UbiXGPBEnum_FieldNumber_OptionsArray = 3,
  UbiXGPBEnum_FieldNumber_SourceContext = 4,
  UbiXGPBEnum_FieldNumber_Syntax = 5,
};

/**
 * Enum type definition.
 **/
UbiX_GPB_FINAL @interface UbiXGPBEnum : UbiXGPBMessage

/** Enum type name. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** Enum value definitions. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UbiXGPBEnumValue*> *enumvalueArray;
/** The number of items in @c enumvalueArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger enumvalueArray_Count;

/** Protocol buffer options. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UbiXGPBOption*> *optionsArray;
/** The number of items in @c optionsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger optionsArray_Count;

/** The source context. */
@property(nonatomic, readwrite, strong, null_resettable) UbiXGPBSourceContext *sourceContext;
/** Test to see if @c sourceContext has been set. */
@property(nonatomic, readwrite) BOOL hasSourceContext;

/** The source syntax. */
@property(nonatomic, readwrite) UbiXGPBSyntax syntax;

@end

/**
 * Fetches the raw value of a @c UbiXGPBEnum's @c syntax property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t UbiXGPBEnum_Syntax_RawValue(UbiXGPBEnum *message);
/**
 * Sets the raw value of an @c UbiXGPBEnum's @c syntax property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void UbiXSetGPBEnum_Syntax_RawValue(UbiXGPBEnum *message, int32_t value);

#pragma mark - UbiXGPBEnumValue

typedef UbiX_GPB_ENUM(UbiXGPBEnumValue_FieldNumber) {
  UbiXGPBEnumValue_FieldNumber_Name = 1,
  UbiXGPBEnumValue_FieldNumber_Number = 2,
  UbiXGPBEnumValue_FieldNumber_OptionsArray = 3,
};

/**
 * Enum value definition.
 **/
UbiX_GPB_FINAL @interface UbiXGPBEnumValue : UbiXGPBMessage

/** Enum value name. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** Enum value number. */
@property(nonatomic, readwrite) int32_t number;

/** Protocol buffer options. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UbiXGPBOption*> *optionsArray;
/** The number of items in @c optionsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger optionsArray_Count;

@end

#pragma mark - UbiXGPBOption

typedef UbiX_GPB_ENUM(UbiXGPBOption_FieldNumber) {
  UbiXGPBOption_FieldNumber_Name = 1,
  UbiXGPBOption_FieldNumber_Value = 2,
};

/**
 * A protocol buffer option, which can be attached to a message, field,
 * enumeration, etc.
 **/
UbiX_GPB_FINAL @interface UbiXGPBOption : UbiXGPBMessage

/**
 * The option's name. For protobuf built-in options (options defined in
 * descriptor.proto), this is the short name. For example, `"map_entry"`.
 * For custom options, it should be the fully-qualified name. For example,
 * `"google.api.http"`.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/**
 * The option's value packed in an Any message. If the value is a primitive,
 * the corresponding wrapper type defined in google/protobuf/wrappers.proto
 * should be used. If the value is an enum, it should be stored as an int32
 * value using the google.protobuf.Int32Value type.
 **/
@property(nonatomic, readwrite, strong, null_resettable) UbiXGPBAny *value;
/** Test to see if @c value has been set. */
@property(nonatomic, readwrite) BOOL hasValue;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
