// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/struct.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(UbiX_GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define UbiX_GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if UbiX_GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/UbiXGPBDescriptor.h>
 #import <Protobuf/UbiXGPBMessage.h>
 #import <Protobuf/UbiXGPBRootObject.h>
#else
 #import "UbiXGPBDescriptor.h"
 #import "UbiXGPBMessage.h"
 #import "UbiXGPBRootObject.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class UbiXGPBListValue;
@class UbiXGPBStruct;
@class UbiXGPBValue;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum UbiXGPBNullValue

/**
 * `NullValue` is a singleton enumeration to represent the null value for the
 * `Value` type union.
 *
 *  The JSON representation for `NullValue` is JSON `null`.
 **/
typedef UbiX_GPB_ENUM(UbiXGPBNullValue) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  UbiXGPBNullValue_GPBUnrecognizedEnumeratorValue = kUbiXGPBUnrecognizedEnumeratorValue,
  /** Null value. */
  UbiXGPBNullValue_NullValue = 0,
};

UbiXGPBEnumDescriptor *UbiXGPBNullValue_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL UbiXGPBNullValue_IsValidValue(int32_t value);

#pragma mark - UbiXGPBStructRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (UbiXGPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c UbiXGPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
UbiX_GPB_FINAL @interface UbiXGPBStructRoot : UbiXGPBRootObject
@end

#pragma mark - UbiXGPBStruct

typedef UbiX_GPB_ENUM(UbiXGPBStruct_FieldNumber) {
  UbiXGPBStruct_FieldNumber_Fields = 1,
};

/**
 * `Struct` represents a structured data value, consisting of fields
 * which map to dynamically typed values. In some languages, `Struct`
 * might be supported by a native representation. For example, in
 * scripting languages like JS a struct is represented as an
 * object. The details of that representation are described together
 * with the proto support for the language.
 *
 * The JSON representation for `Struct` is JSON object.
 **/
UbiX_GPB_FINAL @interface UbiXGPBStruct : UbiXGPBMessage

/** Unordered map of dynamically typed values. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, UbiXGPBValue*> *fields;
/** The number of items in @c fields without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger fields_Count;

@end

#pragma mark - UbiXGPBValue

typedef UbiX_GPB_ENUM(UbiXGPBValue_FieldNumber) {
  UbiXGPBValue_FieldNumber_NullValue = 1,
  UbiXGPBValue_FieldNumber_NumberValue = 2,
  UbiXGPBValue_FieldNumber_StringValue = 3,
  UbiXGPBValue_FieldNumber_BoolValue = 4,
  UbiXGPBValue_FieldNumber_StructValue = 5,
  UbiXGPBValue_FieldNumber_ListValue = 6,
};

typedef UbiX_GPB_ENUM(UbiXGPBValue_Kind_OneOfCase) {
  UbiXGPBValue_Kind_OneOfCase_GPBUnsetOneOfCase = 0,
  UbiXGPBValue_Kind_OneOfCase_NullValue = 1,
  UbiXGPBValue_Kind_OneOfCase_NumberValue = 2,
  UbiXGPBValue_Kind_OneOfCase_StringValue = 3,
  UbiXGPBValue_Kind_OneOfCase_BoolValue = 4,
  UbiXGPBValue_Kind_OneOfCase_StructValue = 5,
  UbiXGPBValue_Kind_OneOfCase_ListValue = 6,
};

/**
 * `Value` represents a dynamically typed value which can be either
 * null, a number, a string, a boolean, a recursive struct value, or a
 * list of values. A producer of value is expected to set one of that
 * variants, absence of any variant indicates an error.
 *
 * The JSON representation for `Value` is JSON value.
 **/
UbiX_GPB_FINAL @interface UbiXGPBValue : UbiXGPBMessage

/** The kind of value. */
@property(nonatomic, readonly) UbiXGPBValue_Kind_OneOfCase kindOneOfCase;

/** Represents a null value. */
@property(nonatomic, readwrite) UbiXGPBNullValue nullValue;

/** Represents a double value. */
@property(nonatomic, readwrite) double numberValue;

/** Represents a string value. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *stringValue;

/** Represents a boolean value. */
@property(nonatomic, readwrite) BOOL boolValue;

/** Represents a structured value. */
@property(nonatomic, readwrite, strong, null_resettable) UbiXGPBStruct *structValue;

/** Represents a repeated `Value`. */
@property(nonatomic, readwrite, strong, null_resettable) UbiXGPBListValue *listValue;

@end

/**
 * Fetches the raw value of a @c UbiXGPBValue's @c nullValue property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t UbiXGPBValue_NullValue_RawValue(UbiXGPBValue *message);
/**
 * Sets the raw value of an @c UbiXGPBValue's @c nullValue property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void UbiXSetGPBValue_NullValue_RawValue(UbiXGPBValue *message, int32_t value);

/**
 * Clears whatever value was set for the oneof 'kind'.
 **/
void UbiXGPBValue_ClearKindOneOfCase(UbiXGPBValue *message);

#pragma mark - UbiXGPBListValue

typedef UbiX_GPB_ENUM(UbiXGPBListValue_FieldNumber) {
  UbiXGPBListValue_FieldNumber_ValuesArray = 1,
};

/**
 * `ListValue` is a wrapper around a repeated field of values.
 *
 * The JSON representation for `ListValue` is JSON array.
 **/
UbiX_GPB_FINAL @interface UbiXGPBListValue : UbiXGPBMessage

/** Repeated field of dynamically typed values. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UbiXGPBValue*> *valuesArray;
/** The number of items in @c valuesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger valuesArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
